' Developer Express Code Central Example:
' How to enable animation for a series template
' 
' This example demonstrates how to animate series that are populated using series
' templates.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E2412
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace WpfChartSeriesTemplateBinding.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As WpfChartSeriesTemplateBinding.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New WpfChartSeriesTemplateBinding.Properties.Settings())), WpfChartSeriesTemplateBinding.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return WpfChartSeriesTemplateBinding.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
